name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  linux-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1 # https://github.com/marketplace/actions/detect-and-tag-new-version#usage
#      - uses: mikefarah/yq@master
      - uses: salsify/action-detect-and-tag-new-version@v2 # https://github.com/marketplace/actions/detect-and-tag-new-version#usage
        with:
          version-command: |
            yq '.version' pubspec.yaml

