name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2 # https://github.com/marketplace/actions/flutter-action
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: flutter analyze
