name: Create release

#on:
#  push:
#    tags:
#      - '*'
on: workflow_dispatch

jobs:
  release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # https://github.com/marketplace/actions/get-latest-tag
      - uses: subosito/flutter-action@v2 # https://github.com/marketplace/actions/flutter-action
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Install dependencies
        run: flutter pub get
      - name: Install build dependencies
        run: sudo apt install -y ninja-build libgtk-3-dev
      - run: flutter doctor
      - name: 'Get Previous tag'
        id: currentTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Build release linux
        run: flutter build linux --release
      - name: Zip release linux
        run: |
          mv build/linux/x64/release/bundle linux-${{ steps.previoustag.outputs.tag }} && \
          zip -r linux-${{ steps.previoustag.outputs.tag }}.zip linux-${{ steps.previoustag.outputs.tag }}
      - uses: ncipollo/release-action@v1 # https://github.com/marketplace/actions/create-release
        with:
          artifacts: linux-${{ steps.previoustag.outputs.tag }}.zip
          tag: ${{ steps.previoustag.outputs.tag }}

