name: Create release

#on:
#  push:
#    tags:
#      - '*'
on: workflow_dispatch

jobs:
  release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2 # https://github.com/marketplace/actions/flutter-action
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Install dependencies
        run: flutter pub get
      - name: flutter doctor
        run: flutter doctor
      - name: Build release linux
        run: |
          flutter build linux --release
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: "release.tar.gz,foo/*.txt"

